---
- hosts: all
  vars: 
    packages: 
      - wget
      - python3
      - git
      - vim
      - curl
      - xrdp
      - nginx
      - python3-pip
      - unzip
      - zip
    chrome_release: "95.0.4638.69"
  tasks: 
    - name: install packages
      become: true
      become_user: root
      apt:
        state: present
        name: "{{ packages }}"
    - name: download teamviewer
      get_url:
        url: https://download.teamviewer.com/download/linux/teamviewer_amd64.deb
        dest: /opt
    - name: install teamviewer
      command: "deb -i /opt/teamviewer_amd64.deb"
    - name: download selenium
      command: "pip3 install selenium"
    - name: download chrome driver
      get_url:
        url: http://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
        dest: /opt
    - name: unzip chrome driver
      command: "unzip /opt/chromedriver_linux64.zip"
      args: 
        chdir: "/usr/local/bin"
