---
- hosts: all
  vars: 
    minecraft_user: mine_user
    minecraft_group: mine_user
    minecraft_version: 1.21.7
    client_mods_dir: "/opt/client-mods/{{ minecraft_version }}"
    resource_packs_dir: "{{ client_mods_dir }}/resource_packs"
    #download_url: https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar
    # Fabric Loader 0.16.14
    download_url: https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.0.3/fabric-installer-1.0.3.exe
    root_user: root
    root_group: root
    fabric_mods:
    # Fabric Mods for 1.21.6
      - https://cdn.modrinth.com/data/8shC1gFX/versions/DHCqyQtH/BetterF3-15.0.0-Fabric-1.21.6.jar
      - https://cdn.modrinth.com/data/XeEZ3fK2/versions/t9um0ii2/freecam-fabric-1.3.4%2Bmc1.21.6.jar
    # Fabric Mods for 1.21.7
      - https://cdn.modrinth.com/data/PFwYNrHb/versions/rUi8unC2/ArmorPoser-fabric-1.21.7-11.0.1.jar
      - https://cdn.modrinth.com/data/N6n5dqoA/versions/CRjwbqnJ/Axiom-4.9.1-for-MC1.21.6.jar
      - https://cdn.modrinth.com/data/G1s2WpNo/versions/Ibeh65i3/BetterThirdPerson-fabric-1.21.5-1.9.0.jar
      - https://cdn.modrinth.com/data/M08ruV16/versions/ODwC9dEb/bobby-5.2.8%2Bmc1.21.6.jar
      #- https://cdn.modrinth.com/data/VSNURh3q/versions/Erjpfj2l/c2me-fabric-mc1.21.7-0.3.4%2Bbeta.1.0.jar 
      - https://cdn.modrinth.com/data/rrwQMaWQ/versions/C7vXzF7v/camerautils-fabric-1.21.7-1.1.0.jar
      - https://cdn.modrinth.com/data/Wb5oqrBJ/versions/dgbLFTG2/chat_heads-0.13.19-fabric-1.21.6.jar
      - https://cdn.modrinth.com/data/6KrNtW32/versions/Yn2ePslQ/chatsigninghider-fabric-1.21.7-1.0.5.jar
      - https://cdn.modrinth.com/data/4I1XuqiY/versions/N0YnseYc/entity_model_features_fabric_1.21.6-2.4.4.jar
      - https://cdn.modrinth.com/data/BVzZfTc1/versions/aEVKKdXX/entity_texture_features_fabric_1.21.6-6.2.14.jar
      - https://cdn.modrinth.com/data/NNAgCjsB/versions/wxuS4Die/entityculling-fabric-1.8.1-mc1.21.6.jar
      - https://cdn.modrinth.com/data/P7dR8mSH/versions/JntuF9Ul/fabric-api-0.129.0%2B1.21.7.jar
      - https://cdn.modrinth.com/data/Ht0RRAt0/versions/DpQOLtpy/fasttrading-0.2.3%2B1.21.6.jar
      - https://cdn.modrinth.com/data/5ZwdcRci/versions/riHCXrIc/ImmediatelyFast-Fabric-1.11.1%2B1.21.7.jar
      - https://cdn.modrinth.com/data/JygyCSA4/versions/hvzvjsCL/itemscroller-fabric-1.21.7-0.28.1.jar
      - https://cdn.modrinth.com/data/RPOSBQgq/versions/UhsO4Lxe/itemswapper-fabric-0.8.0-mc1.21.6.jar
      - https://cdn.modrinth.com/data/bEpr0Arc/versions/PHUdsjfV/litematica-fabric-1.21.7-0.23.1.jar
      - https://cdn.modrinth.com/data/gvQqBUqZ/versions/77EtzYFA/lithium-fabric-0.18.0%2Bmc1.21.7.jar
      - https://cdn.modrinth.com/data/GcWjdA9I/versions/EcW3wuWQ/malilib-fabric-1.21.7-0.25.1.jar
      - https://cdn.modrinth.com/data/UMxybHE8/versions/8VRgdYoh/minihud-fabric-1.21.7-0.36.1.jar
      - https://cdn.modrinth.com/data/mOgUt4GM/versions/JY1tNj8H/modmenu-15.0.0-beta.3.jar
      - https://cdn.modrinth.com/data/51shyZVL/versions/ESxkwc6w/moreculling-fabric-1.21.6-1.4.0-beta.1.jar
      - https://cdn.modrinth.com/data/ccKDOlHs/versions/j6tLZX6U/owo-lib-0.12.21%2B1.21.6.jar
      - https://cdn.modrinth.com/data/TnOXNf5e/versions/4TpqcXzr/peek-fabric-1.21.7-1.4.5.jar
      - https://cdn.modrinth.com/data/nCQRBEiR/versions/31FXpLlF/raised-fabric-1.21.6-5.0.0.jar
      - https://cdn.modrinth.com/data/fCpuZIcM/versions/m2zfdLA7/resourcepackchecker-fabric-1.21.7-1.2.2.jar
      - https://cdn.modrinth.com/data/2M01OLQq/versions/os3K6gc6/shulkerboxtooltip-fabric-5.2.8%2B1.21.7.jar
      - https://cdn.modrinth.com/data/AANobbMI/versions/ND4ROcMQ/sodium-fabric-0.6.13%2Bmc1.21.6.jar
      - https://cdn.modrinth.com/data/b93awgkg/versions/UxbUjpuC/status-fabric-1.21.7-1.0.8.jar
      - https://cdn.modrinth.com/data/9eGKb6K1/versions/YjxCZ3Wx/voicechat-fabric-1.21.7-2.5.34.jar
      - https://cdn.modrinth.com/data/1u6JkXh5/versions/6stG33I5/worldedit-mod-7.3.15.jar

    resource_packs:
      - https://cdn.modrinth.com/data/50dA9Sha/versions/9LtDLleW/FreshAnimations_v1.9.4.zip
      - https://cdn.modrinth.com/data/BBx79tDa/versions/hVLDqZj2/My%20Minimal%20Armor%201.21.5.zip

    vanilla_tweaks_post_url: "https://vanillatweaks.net/assets/server/zipdatapacks.php"
    decorative_cosmetic: ["wandering trades", "armor statues", "more mob heads", "player head drops", "silence mobs"]
    informative: ["spawning spheres", "wandering trader announcements", "durability ping"]
    packs_json: |
          {"decorative-cosmetic": {{ decorative_cosmetic | to_json }}, "informative": {{ informative | to_json }}}
    vanilla_tweaks_body: "packs={{ packs_json | urlencode }}&version=1.21"
    vanilla_tweaks_download_dest: "{{ resource_packs_dir }}/VanillaTweaks_UNZIP_ME.zip"
  tasks:

    - name: create mod directory
      file:
        path: "{{ client_mods_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"
    
    - name: create resource packs directory
      file:
        path: "{{ resource_packs_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"

    - name: download minecraft
      get_url: 
        url: "{{ download_url }}"
        dest: "{{ client_mods_dir }}/server.jar"
      become: true
      become_user: "{{ minecraft_user }}"
    
    - name: install mods
      get_url:
        url: "{{ item }}"
        dest: "{{ client_mods_dir }}/{{ item | basename }}"
      with_items: "{{ fabric_mods }}"
      become: true
      become_user: "{{ minecraft_user }}"
    
    - name: download the resource packs
      get_url:
        url: "{{ item }}"
        dest: "{{ resource_packs_dir }}/{{ item | basename }}"
      with_items: "{{ resource_packs }}"
      become: true
      become_user: "{{ minecraft_user }}"

    - name: Prepare POST body for VanillaTweaks
      uri:
        url: "{{ vanilla_tweaks_post_url }}"
        method: POST
        body_format: form-urlencoded
        body: "{{ vanilla_tweaks_body }}"
        return_content: yes
        status_code: 200
      register: vanilla_tweaks_post_response

    - name: Validate response contains 'link'
      fail:
        msg: "The response does not contain a 'link' attribute: {{ vanilla_tweaks_post_response }}"
      when: vanilla_tweaks_post_response.json.link is not defined

    - name: Extract download URL from response
      set_fact:
        download_url: "https://vanillatweaks.net{{ vanilla_tweaks_post_response.json.link }}"

    - name: Download file from received URL
      get_url:
        url: "{{ download_url }}"
        dest: "{{ vanilla_tweaks_download_dest }}"
      become: true
      become_user: "{{ minecraft_user }}"

    - name: Create zip for client mod download
      archive:
        path: "{{ client_mods_dir }}"
        dest: "{{ client_mods_dir }}/../client-mods-{{ minecraft_version }}.zip"
        format: zip
      become: true
      become_user: "{{ minecraft_user }}"

    # - name: Clean up temporary files
    #   file:
    #     path: "{{ resource_packs_dir }}/*.zip"
    #     state: absent
    #   become: true
    #   become_user: "{{ minecraft_user }}"   
    # - name: Clean up mods
    #   file:
    #     path: "{{ client_mods_dir }}/*.jar"
    #     state: absent
    #   become: true
    #   become_user: "{{ minecraft_user }}"

    - name: Setup Complete
      debug:
        msg: "Setup Complete"

