---
- hosts: all
  vars: 
    minecraft_user: mine_user
    minecraft_group: mine_user
    minecraft_version: 1.21.11
    client_mods_dir: "/opt/client-mods/{{ minecraft_version }}"
    resource_packs_dir: "{{ client_mods_dir }}/resource_packs"
    #download_url: https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar
    # Fabric Loader 0.16.14
    download_url: https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.1.1/fabric-installer-1.1.1.exe
    root_user: root
    root_group: root
    fabric_mods:
    # Fabric Mods for 1.21.7
      #- https://cdn.modrinth.com/data/VSNURh3q/versions/Erjpfj2l/c2me-fabric-mc1.21.7-0.3.4%2Bbeta.1.0.jar 
    # Fabric Mods for 1.21.8
      - https://cdn.modrinth.com/data/G1s2WpNo/versions/Ibeh65i3/BetterThirdPerson-fabric-1.21.5-1.9.0.jar
    # Fabric Mods for 1.21.11
    # Fabric Mods for 1.21.10
      - https://cdn.modrinth.com/data/kPkTtp4N/versions/7qLQenlv/coordfinder-fabric-1.21.10-1.1.0.jar
    # Fabric Mods for 1.21.11
      - https://cdn.modrinth.com/data/PFwYNrHb/versions/nkNfOD50/ArmorPoser-fabric-1.21.11-13.1.0.jar
      - https://cdn.modrinth.com/data/N6n5dqoA/versions/M0Jr2ivY/Axiom-5.2.1-for-MC1.21.11.jar
      - https://cdn.modrinth.com/data/8shC1gFX/versions/Qw1nhj7u/BetterF3-17.0.0-Fabric-1.21.11.jar
      - https://cdn.modrinth.com/data/M08ruV16/versions/y6wx9vV9/bobby-5.2.11%2Bmc1.21.11.jar
      - https://cdn.modrinth.com/data/rrwQMaWQ/versions/iTsiAfu8/camerautils-fabric-1.21.11-1.1.2.jar
      - https://cdn.modrinth.com/data/Wb5oqrBJ/versions/AAR2TTo3/chat_heads-1.2.1-fabric-1.21.11.jar
      - https://cdn.modrinth.com/data/6KrNtW32/versions/MpRmljFg/chatsigninghider-fabric-1.21.11-1.0.5.jar
      - https://cdn.modrinth.com/data/NNAgCjsB/versions/Dx3xsUER/entityculling-fabric-1.9.5-mc1.21.11.jar
      - https://cdn.modrinth.com/data/4I1XuqiY/versions/3xCY6scW/entity_model_features_1.21.11-fabric-3.0.11.jar
      - https://cdn.modrinth.com/data/BVzZfTc1/versions/3uFr0jys/entity_texture_features_1.21.11-fabric-7.0.9.jar
      - https://cdn.modrinth.com/data/Ht0RRAt0/versions/A4qWypSp/FastTrading-0.2.3%2B1.21.11.jar
      - https://cdn.modrinth.com/data/XeEZ3fK2/versions/34bZL2kK/freecam-fabric-1.3.6%2Bmc1.21.11.jar
      - https://cdn.modrinth.com/data/P7dR8mSH/versions/i5tSkVBH/fabric-api-0.141.3%2B1.21.11.jar
      - https://cdn.modrinth.com/data/5ZwdcRci/versions/QwkfUKSj/ImmediatelyFast-Fabric-1.14.2%2B1.21.11.jar
      - https://cdn.modrinth.com/data/JygyCSA4/versions/I9Ginfp2/itemscroller-fabric-1.21.11-0.30.0.jar
      - https://cdn.modrinth.com/data/RPOSBQgq/versions/mToG8S6G/itemswapper-fabric-0.8.5-mc1.21.11.jar
      - https://cdn.modrinth.com/data/gvQqBUqZ/versions/qvNsoO3l/lithium-fabric-0.21.3%2Bmc1.21.11.jar
      - https://cdn.modrinth.com/data/bEpr0Arc/versions/zoLjBabk/litematica-fabric-1.21.11-0.25.4.jar
      - https://cdn.modrinth.com/data/GcWjdA9I/versions/jsdKvp3x/malilib-fabric-1.21.11-0.27.5.jar
      - https://cdn.modrinth.com/data/UMxybHE8/versions/9AEkCyqe/minihud-fabric-1.21.11-0.38.2.jar
      - https://cdn.modrinth.com/data/mOgUt4GM/versions/JWQVh32x/modmenu-17.0.0-beta.2.jar
      - https://cdn.modrinth.com/data/51shyZVL/versions/kWU8mVq5/moreculling-fabric-1.21.11-1.6.1.jar
      - https://cdn.modrinth.com/data/ccKDOlHs/versions/33Ei8Thm/owo-lib-0.13.0%2B1.21.11.jar
      - https://cdn.modrinth.com/data/TnOXNf5e/versions/dWLOrrLE/peek-fabric-1.21.11-1.4.9.jar
      - https://cdn.modrinth.com/data/nCQRBEiR/versions/lgLBYQO3/raised-fabric-1.21.11-5.1.2.jar
      - https://cdn.modrinth.com/data/fCpuZIcM/versions/GNRQpK2e/resourcepackchecker-fabric-1.21.11-1.2.2.jar
      - https://cdn.modrinth.com/data/AANobbMI/versions/1OWNgWVR/sodium-fabric-0.8.4%2Bmc1.21.11.jar
      - https://cdn.modrinth.com/data/2M01OLQq/versions/2lPKqJBJ/shulkerboxtooltip-fabric-5.2.15%2B1.21.11.jar
      - https://cdn.modrinth.com/data/b93awgkg/versions/Dw8gVR1R/status-fabric-1.21.11-1.1.0.jar
      - https://cdn.modrinth.com/data/9eGKb6K1/versions/pFTZ8sqQ/voicechat-fabric-1.21.11-2.6.12.jar
      - https://cdn.modrinth.com/data/1u6JkXh5/versions/o645q0Oo/worldedit-mod-7.4.0.jar
    resource_packs:
      - https://cdn.modrinth.com/data/50dA9Sha/versions/F9QwVhGH/FreshAnimations_v1.10.3.zip
      - https://cdn.modrinth.com/data/YAVTU8mK/versions/hGa4E44T/FA%2BAll_Extensions-v1.7.zip
      - https://cdn.modrinth.com/data/BBx79tDa/versions/bT3ZOKe1/my-minimal-armor-1.21.11-v1.4.zip

    vanilla_tweaks_post_url: "https://vanillatweaks.net/assets/server/zipdatapacks.php"
    decorative_cosmetic: ["wandering trades", "armor statues", "more mob heads", "player head drops", "silence mobs"]
    informative: ["spawning spheres", "wandering trader announcements", "durability ping"]
    packs_json: |
          {"decorative-cosmetic": {{ decorative_cosmetic | to_json }}, "informative": {{ informative | to_json }}}
    vanilla_tweaks_body: "packs={{ packs_json | urlencode }}&version=1.21"
    vanilla_tweaks_download_dest: "{{ resource_packs_dir }}/VanillaTweaks_UNZIP_ME.zip"
  tasks:

    - name: create mod directory
      file:
        path: "{{ client_mods_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"
    
    - name: create resource packs directory
      file:
        path: "{{ resource_packs_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"

    - name: download minecraft
      get_url: 
        url: "{{ download_url }}"
        dest: "{{ client_mods_dir }}/fabric-installer.exe"
      become: true
      become_user: "{{ minecraft_user }}"
    
    - name: install mods
      get_url:
        url: "{{ item }}"
        dest: "{{ client_mods_dir }}/{{ item | basename }}"
      with_items: "{{ fabric_mods }}"
      become: true
      become_user: "{{ minecraft_user }}"
    
    - name: download the resource packs
      get_url:
        url: "{{ item }}"
        dest: "{{ resource_packs_dir }}/{{ item | basename }}"
      with_items: "{{ resource_packs }}"
      become: true
      become_user: "{{ minecraft_user }}"

    - name: Prepare POST body for VanillaTweaks
      uri:
        url: "{{ vanilla_tweaks_post_url }}"
        method: POST
        body_format: form-urlencoded
        body: "{{ vanilla_tweaks_body }}"
        return_content: yes
        status_code: 200
      register: vanilla_tweaks_post_response

    - name: Validate response contains 'link'
      fail:
        msg: "The response does not contain a 'link' attribute: {{ vanilla_tweaks_post_response }}"
      when: vanilla_tweaks_post_response.json.link is not defined

    - name: Extract download URL from response
      set_fact:
        download_url: "https://vanillatweaks.net{{ vanilla_tweaks_post_response.json.link }}"

    - name: Download file from received URL
      get_url:
        url: "{{ download_url }}"
        dest: "{{ vanilla_tweaks_download_dest }}"
      become: true
      become_user: "{{ minecraft_user }}"

    - name: Create zip for client mod download
      archive:
        path: "{{ client_mods_dir }}"
        dest: "{{ client_mods_dir }}/../client-mods-{{ minecraft_version }}.zip"
        format: zip
      become: true
      become_user: "{{ minecraft_user }}"

    # - name: Clean up temporary files
    #   file:
    #     path: "{{ resource_packs_dir }}/*.zip"
    #     state: absent
    #   become: true
    #   become_user: "{{ minecraft_user }}"   
    # - name: Clean up mods
    #   file:
    #     path: "{{ client_mods_dir }}/*.jar"
    #     state: absent
    #   become: true
    #   become_user: "{{ minecraft_user }}"

    - name: Setup Complete
      debug:
        msg: "Setup Complete"

