---
- hosts: all
  vars: 
    packages: 
      - wget
      - python3
      - git
      - vim
      - curl
      - python3-pip
      - tmux
      - rsyslog
      - whois
      - lame-libs
    minecraft_user: mine_user
    minecraft_group: mine_user
    minecraft_home: /opt/minecraft
    backup_dir: /opt/backups
    #level_seed: -7497863297697545553
    level_seed: 5103687417315433447
    motd_message: "The HolmesCraft Server"
    spawn_protection: 0
    difficulty: hard
    level_name: "world"
    view_distance: 32
    minecraft_version: 1.21.5
    #download_url: https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar
    # Fabric Loader 0.16.14
    download_url: https://meta.fabricmc.net/v2/versions/loader/1.21.5/0.16.14/1.0.3/server/jar
    root_user: root
    root_group: root
    fabric_mods:
      - https://cdn.modrinth.com/data/NSBscIsQ/versions/GVIjoeE5/inhabitor-fabric-1.21.5-1.0.5.jar
      - https://cdn.modrinth.com/data/fQEb0iXm/versions/neW85eWt/krypton-0.2.9.jar
      - https://cdn.modrinth.com/data/b93awgkg/versions/xGzIBi5L/status-fabric-1.21.5-1.0.8.jar
      - https://cdn.modrinth.com/data/1LE7mid6/versions/rL3BEGRg/instantgroup-fabric-1.21.5-1.7.0.jar
      - https://cdn.modrinth.com/data/9s6osm5g/versions/qA00xo1O/cloth-config-18.0.145-fabric.jar
      - https://cdn.modrinth.com/data/nxrXbh5K/versions/eodk4JxM/viewdistancefix-fabric-1.21.5-1.0.2.jar
      - https://cdn.modrinth.com/data/YoRtMPzM/versions/OqUZogW2/SHA1Runtime-1.21.5-1.3.0.jar
      - https://cdn.modrinth.com/data/PFwYNrHb/versions/NQwyaWBX/ArmorPoser-fabric-1.21.5-9.0.1.jar
      - https://cdn.modrinth.com/data/9nFfpUyI/versions/G44aJZ1W/datapack-injector-fabric-1.0.0%2B1.21.5.jar
      - https://cdn.modrinth.com/data/TnOXNf5e/versions/JTPPwvdu/peek-fabric-1.21.5-1.4.2.jar
      - https://cdn.modrinth.com/data/P7dR8mSH/versions/hBmLTbVB/fabric-api-0.121.0%2B1.21.5.jar
      - https://cdn.modrinth.com/data/gvQqBUqZ/versions/VWYoZjBF/lithium-fabric-0.16.2%2Bmc1.21.5.jar
      - https://cdn.modrinth.com/data/kPkTtp4N/versions/geHUXs1Q/coordfinder-fabric-1.21.5-1.1.0.jar
      - https://cdn.modrinth.com/data/9eGKb6K1/versions/suJqF5xU/voicechat-fabric-1.21.5-2.5.30.jar
      - https://cdn.modrinth.com/data/uXXizFIs/versions/CtMpt7Jr/ferritecore-8.0.0-fabric.jar
      - https://cdn.modrinth.com/data/SRlzjEBS/versions/gJYpGwtr/audioplayer-fabric-1.21.5-1.13.2.jar
      - https://cdn.modrinth.com/data/l6YH9Als/versions/NURCAL12/spark-1.10.128-fabric.jar
      - https://cdn.modrinth.com/data/e0M1UDsY/versions/aCWSF57s/collective-1.21.5-8.3.jar
      - https://cdn.modrinth.com/data/cz5Ve1NT/versions/EVEA3oXs/player-drops-head-v.3.3.1.jar
      - https://cdn.modrinth.com/data/XeEZ3fK2/versions/pnqW0YaL/freecam-fabric-1.3.3%2Bmc1.21.5.jar
      - https://cdn.modrinth.com/data/jzTUm9hE/versions/hbgvhaSJ/justmobheads-1.21.5-8.6.jar
    data_packs:
      - https://cdn.modrinth.com/data/1s7zUX2O/versions/wYCFk3EJ/name_formatting_station_v2.6.zip
      - https://cdn.modrinth.com/data/Cfqq3Wh1/versions/ekYrKM2N/armor_statues_v2.15.0.zip
      - https://cdn.modrinth.com/data/v1U62WLz/versions/Cylr4gal/Statistic-Books-MC_v1.6.zip
      - https://cdn.modrinth.com/data/2pK3w13d/versions/9hCPx2N1/custom_roleplay_data_v1.5.zip

    vanilla_tweaks_post_url: "https://vanillatweaks.net/assets/server/zipdatapacks.php"
    vanilla_tweaks_post_data:
      decorative-cosmetic:
        - "wandering+trades"
        - "armor+statues"
        - "more+mob+heads"
        - "player+head+drops"
        - "silence+mobs"
      informative:
        - "spawning+spheres"
        - "wandering+trader+announcements"
        - "durability+ping"
    vanilla_tweaks_download_dest: "/tmp/VanillaTweaks_UNZIP_ME.zip"
    tmux_session: minecraft
    tmux_window: fabric
    java_opts: "-server -Xmx8G -Xms8G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1"
    #og_opts: "-server -Xmx8G -Xms8G -XX:+UseZGC -XX:+ZGenerational"
  tasks: 
    - name: stop minecraft if started
      systemd:
        name: minecraft-server
        state: stopped
        enabled: no
      ignore_errors: yes
      become: true
      become_user: "{{ root_user }}"
    - name: update cache on Ubuntu
      when: ansible_os_family == "Debian"
      become: true
      become_user: "{{ root_user }}"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
    - name: update cache on RedHat
      when: ansible_os_family == "RedHat"
      become: true
      become_user: "{{ root_user }}"
      dnf:
        update_cache: yes
    - name: install packages on Ubuntu
      when: ansible_os_family == "Debian"
      become: true
      become_user: "{{ root_user }}"
      apt:
        state: present
        name: "{{ packages }}"
    - name: install packages on RedHat
      when: ansible_os_family == "RedHat"
      become: true
      become_user: "{{ root_user }}"
      dnf:
        state: present
        name: "{{ packages }}"
    - name: install Java on Ubuntu
      when: ansible_os_family == "Debian"
      become: true
      become_user: "{{ root_user }}"
      apt:
        name: openjdk-21-jdk
        state: present
    - name: install Java on RedHat
      when: ansible_os_family == "RedHat"
      become: true
      become_user: "{{ root_user }}"
      dnf:
        name: jdk-21-headless
        state: present
    - name: create password for minecraft user
      shell: openssl passwd -1 -salt $(openssl rand -base64 6) "{{ minecraft_user }}" | cut -d':' -f2
      register: hashed_password
    - name: create minecraft group
      group: 
        state: present
        name: "{{ minecraft_group }}"
        system: yes
      become: true
      become_user: "{{ root_user }}"
    - name: create minecraft user
      user: 
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        comment: Minecraft User
        shell: /bin/bash
        password: "{{ hashed_password.stdout }}"
        state: present
      become: true
      become_user: "{{ root_user }}"
    - name: create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"
    - name: create minecraft directory
      file: 
        path: "{{ minecraft_home }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"
    - name: download minecraft
      get_url: 
        url: "{{ download_url }}"
        dest: "{{ minecraft_home }}/server.jar"
      become: true
      become_user: "{{ minecraft_user }}"
    - name: check if server.properties and eula.txt exist
      stat:
        path: "{{ minecraft_home }}/server.properties"
      register: server_properties
      become: true
      become_user: "{{ minecraft_user }}"
    - name: check if eula.txt exists
      stat: 
        path: "{{ minecraft_home }}/eula.txt"
      register: eula
      become: true
      become_user: "{{ minecraft_user }}"
    - name: initial run to generate eula and server.properties
      shell: echo "stop" | java -jar {{ minecraft_home }}/server.jar nogui
      args:
        chdir: "{{ minecraft_home }}"
      become: true
      become_user: "{{ minecraft_user }}"
      ignore_errors: yes
      when: eula.stat.exists == false or server_properties.stat.exists == false
    - name: accept EULA
      lineinfile:
        path: "{{ minecraft_home }}/eula.txt"
        regexp: '^eula=false'
        line: eula=true
      become: true
      become_user: "{{ minecraft_user }}"
    - name: set seed
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^level-seed='
        line: level-seed={{ level_seed }}
      become: true
      become_user: "{{ minecraft_user }}"
    - name: set motd
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^motd='
        line: motd={{ motd_message }}
      become: true  
      become_user: "{{ minecraft_user }}"
    - name: set level name
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^level-name='
        line: level-name={{ level_name }}
      become: true
      become_user: "{{ minecraft_user }}"
    - name: set view distance
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^view-distance='
        line: view-distance={{ view_distance }}
      become: true
      become_user: "{{ minecraft_user }}"
    - name: set spawn protection
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^spawn-protection='
        line: spawn-protection={{ spawn_protection }}
      become: true
      become_user: "{{ minecraft_user }}"
    - name: set difficuly to hard
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^difficulty='
        line: difficulty={{ difficulty }}
      become: true
      become_user: "{{ minecraft_user }}"
    - name: create systemd service
      template: 
        src: minecraft-server.service 
        dest: /etc/systemd/system/minecraft-server.service
        owner: "{{ root_user }}"
        group: "{{ root_group }}"
      become: true
      become_user: "{{ root_user }}"
    - name: create start script
      template:
        src: minecraft-server-start.sh
        dest: "{{ minecraft_home }}/minecraft-server-start.sh"
        mode: 0755
      become: true
      become_user: "{{ minecraft_user }}"
    - name: create stop script
      template:
        src: minecraft-server-stop.sh
        dest: "{{ minecraft_home }}/minecraft-server-stop.sh"
        mode: 0755
      become: true
      become_user: "{{ minecraft_user }}"
    - name: create setup script
      template:
        src: setup-minecraft-server.sh
        dest: "{{ minecraft_home }}/setup-minecraft-server.sh"
        mode: 0755
      become: true
      become_user: "{{ minecraft_user }}"
    - name: setup backup script
      template:
        src: backup-minecraft-server.sh
        dest: "{{ minecraft_home }}/backup-minecraft-server.sh"
        mode: 0755
      become: true
      become_user: "{{ minecraft_user }}"
    - name: setup whitelist file
      template:
        src: whitelist.json
        dest: "{{ minecraft_home }}/whitelist.json"
        mode: 0644
      become: true
      become_user: "{{ minecraft_user }}"
    - name: install mods
      get_url:
        url: "{{ item }}"
        dest: "{{ minecraft_home }}/mods/{{ item | basename }}"
      with_items: "{{ fabric_mods }}"
      become: true
      become_user: "{{ minecraft_user }}"
    - name: ensure world and datapacks directories exist
      file:
        path: "{{ minecraft_home }}/{{ level_name }}/datapacks"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ minecraft_user }}"
    - name: download the data packs
      get_url:
        url: "{{ item }}"
        dest: "{{ minecraft_home }}/{{ level_name }}/datapacks/{{ item | basename }}"
      with_items: "{{ data_packs }}"
      become: true
      become_user: "{{ minecraft_user }}"

    - name: POST data to VanillaTweaks and get response
      uri:
        url: "{{ vanilla_tweaks_post_url }}"
        method: POST
        body_format: json
        body: "{{ vanilla_tweaks_post_data }}"
        return_content: yes
        status_code: 200
      register: vanilla_tweaks_post_response

    - name: Extract download URL from response
      set_fact:
        download_url: "https://vanillatweaks.net{{ vanilla_tweaks_post_response.json.link }}"

    - name: Download file from received URL
      get_url:
        url: "{{ download_url }}"
        dest: "{{ vanilla_tweaks_download_dest }}"

    - name: download and unzip the vanilla tweaks data packs
      unarchive:
        src: "{{ vanilla_tweaks_download_dest }}"
        dest: "{{ minecraft_home }}/{{ level_name }}/datapacks"
      become: true
      become_user: "{{ minecraft_user }}"

    - name: enable and start minecraft-server
      systemd:
        name: minecraft-server
        enabled: yes
        state: started
      become: true
      become_user: "{{ root_user }}"
    - name: validate server is up and running by checking the logs
      shell: tail -n 20 {{ minecraft_home }}/logs/latest.log
      register: server_logs
      until: '"[Server thread/INFO]: Done" in server_logs.stdout'
      retries: 10
      delay: 5
      become: true
      become_user: "{{ minecraft_user }}"
    - name: run final server setup script
      shell: "{{ minecraft_home }}/setup-minecraft-server.sh"
      become: true
      become_user: "{{ root_user }}"
    - name: setup hourly cron job for backups
      cron:
        name: "backup-minecraft-server"
        job: "{{ minecraft_home }}/backup-minecraft-server.sh"
        minute: 0
        hour: "*"
        user: "{{ minecraft_user }}"
      become: true
      become_user: "{{ root_user }}"
    - name: Copy Minecraft Firewalld service file
      template:
        src: minecraft.xml
        dest: /etc/firewalld/services/minecraft.xml
        mode: '0644'
      become: true
      become_user: "{{ root_user }}"
    - name: Reload Firewalld to apply new service
      command: firewall-cmd --reload
      become: true
      become_user: "{{ root_user }}"
    - name: Enable Minecraft Firewalld service
      firewalld:
        service: minecraft
        permanent: yes
        state: enabled
      become: true
      become_user: "{{ root_user }}"
    - name: Reload Firewalld after enabling service
      command: firewall-cmd --reload
      become: true
      become_user: "{{ root_user }}"
    - name: Setup Complete
      debug: 
        msg: "Setup Complete"

