---
- hosts: all
  vars: 
    packages: 
      - wget
      - python3
      - git
      - vim
      - curl
      - python3-pip
      - openjdk-21-jdk
      - tmux
      - rsyslog
    minecraft_user: mine_user
    minecraft_group: mine_user
    minecraft_home: /opt/minecraft
    level_seed: -7497863297697545553
    # Version 1.21.4
    #download_url: https://piston-data.mojang.com/v1/objects/4707d00eb834b446575d89a61a11b5d548d8c001/server.jar
    # Fabric Loader 0.16.10
    download_url: https://meta.fabricmc.net/v2/versions/loader/1.21.4/0.16.10/1.0.1/server/jar
    root_user: root
  tasks: 
    - name: create minecraft group
      group: 
        state: present
        name: "{{ minecraft_group }}"
        system: yes
      become: true
      become_user: "{{ root_user }}"
    - name: create minecraft user
      user: 
        name: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
        comment: Minecraft User
        password: passw0rd
        state: present
      become: true
      become_user: "{{ root_user }}"
    - name: update cache
      become: true
      become_user: "{{ root_user }}"
      apt: 
        update_cache: yes
        cache_valid_time: 3600
    - name: install packages
      become: true
      become_user: "{{ root_user }}"
      apt:
        state: present
        name: "{{ packages }}"
    - name: create minecraft directory
      file: 
        path: "{{ minecraft_home }}"
        state: directory
        mode: '0755'
        owner: "{{ minecraft_user }}"
        group: "{{ minecraft_group }}"
      become: true
      become_user: "{{ root_user }}"
    - name: download minecraft
      get_url: 
        url: "{{ download_url }}"
        dest: "{{ minecraft_home }}/server.jar"
      become: true
      become_user: "{{ minecraft_user }}"
    - name: initial run to generate eula and server.properties
      shell: echo "stop" | java -jar {{ minecraft_home }}/server.jar nogui
      args:
        chdir: "{{ minecraft_home }}"
      become: true
      become_user: "{{ minecraft_user }}"
    - name: accept EULA
      lineinfile:
        path: "{{ minecraft_home }}/eula.txt"
        regexp: '^eula=false'
        line: eula=true
      become: true
      become_user: "{{ minecraft_user }}"
    - name: set seed
      lineinfile:
        path: "{{ minecraft_home }}/server.properties"
        regexp: '^level-seed='
        line: level-seed={{ level_seed }}
      become: true
      become_user: "{{ minecraft_user }}"
    #- name: setup permissions
    - name: create systemd service
      template: 
        src: minecraft-server.service 
        dest: /etc/systemd/system/minecraft-server.service
        owner: "{{ root_user }}"
        group: "{{ root_user }}"
      become: true
      become_user: "{{ root_user }}"
    - name: create start script
      template:
        src: minecraft-server-start.sh
        dest: "{{ minecraft_home }}/minecraft-server-start.sh"
        owner: "{{ root_user }}"
        group: "{{ root_user }}"
        mode: 0755
      become: true
      become_user: "{{ root_user }}"
    - name: create stop script
      template:
        src: minecraft-server-stop.sh
        dest: "{{ minecraft_home }}/minecraft-server-stop.sh"
        owner: "{{ root_user }}"
        group: "{{ root_user }}"
        mode: 0755
      become: true
      become_user: "{{ root_user }}"
    - name: Setup Complete
      debug: 
        msg: "Setup Complete"

